---
.devcontainer:
  delete: true
appveyor.yml:
  delete: true
.gitlab-ci.yml:
  delete: true
.travis.yml:
  delete: true
.gitignore:
  paths:
    - /.devcontainer
    - /spec/fixtures/docker_provision/.terraform*
    - /spec/fixtures/docker_provision/terraform.tfstate*
.rubocop.yml:
  default_configs:
    RSpec/NamedSubject:
      Enabled: false
    RSpec/SubjectStub:
      Enabled: false
    RSpec/BeforeAfterAll:
      Exclude:
        - spec/integration/**/*.rb
